<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>aspnet-Jeux_Olympiques-5a81ba59-b0c8-44ac-9dbf-a76f99610f50</UserSecretsId>
    <GenerateDocumentationFile>False</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="wwwroot\NewFolder1\**" />
    <Compile Remove="wwwroot\NewFolder2\**" />
    <Compile Remove="wwwroot\NewFolder3\**" />
    <Compile Remove="wwwroot\NewFolder\**" />
    <Compile Remove="UnitTests\**" />
    <Content Remove="wwwroot\NewFolder1\**" />
    <Content Remove="wwwroot\NewFolder2\**" />
    <Content Remove="wwwroot\NewFolder3\**" />
    <Content Remove="wwwroot\NewFolder\**" />
    <Content Remove="UnitTests\**" />
    <EmbeddedResource Remove="wwwroot\NewFolder1\**" />
    <EmbeddedResource Remove="wwwroot\NewFolder2\**" />
    <EmbeddedResource Remove="wwwroot\NewFolder3\**" />
    <EmbeddedResource Remove="wwwroot\NewFolder\**" />
    <EmbeddedResource Remove="UnitTests\**" />
    <None Remove="wwwroot\NewFolder1\**" />
    <None Remove="wwwroot\NewFolder2\**" />
    <None Remove="wwwroot\NewFolder3\**" />
    <None Remove="wwwroot\NewFolder\**" />
    <None Remove="UnitTests\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="8.0.10" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.10" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="8.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.10">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.10" />
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="8.0.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.10">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration" Version="8.0.6" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="8.0.6" />
    <PackageReference Include="QRCoder" Version="1.6.0" />
    <PackageReference Include="SendGrid" Version="9.29.3" />
  </ItemGroup>

</Project>
