// <auto-generated />
using System;
using Jeux_Olympiques.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Jeux_Olympiques.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260814220448_InitialCreateMySql")]
    partial class InitialCreateMySql
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Jeux_Olympiques.Areas.Identity.Data.Jeux_OlympiquesUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("AccountKey")
                        .HasColumnType("longtext");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("varchar(21)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("FirstName")
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator().HasValue("Jeux_OlympiquesUser");

                    b.UseTphMappingStrategy();

                    b.HasData(
                        new
                        {
                            Id = "1DBFDCBB-4D11-4562-9756-602889FD4163",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "05e593f3-cb5b-4597-a926-e9bbf804289f",
                            Email = "admin@jeuxolympiques.com",
                            EmailConfirmed = true,
                            FirstName = "AdminPrenom",
                            LastName = "AdminNom",
                            LockoutEnabled = true,
                            NormalizedEmail = "ADMIN@JEUXOLYMPIQUES.COM",
                            NormalizedUserName = "ADMIN@JEUXOLYMPIQUES.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEG1swvJSZyrab4nmV8Dl1AaNZIz/Owlf9869lZ7X0Vxr3DCd/XzSutmpTNTMddrNjA==",
                            PhoneNumber = "NULL",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "65K4MQIYK4OSUVYHUY46KRXZ3EUBNO6R",
                            TwoFactorEnabled = false,
                            UserName = "admin@jeuxolympiques.com"
                        },
                        new
                        {
                            Id = "c7a42f97-4108-4ff9-bdee-326866513a03",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "3967ca6c-926b-4610-93f8-e4ee58de29ef",
                            Email = "user@jeuxolympiques.com",
                            EmailConfirmed = true,
                            FirstName = "Franck",
                            LastName = "Letesteur",
                            LockoutEnabled = true,
                            NormalizedEmail = "USER@JEUXOLYMPIQUES.COM",
                            NormalizedUserName = "USER@JEUXOLYMPIQUES.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEAuQECgPLnpmQ3uGf3DY87bFAf1ny8toJ0OsyDbLnnruDv3QdxbYUe273bLsX39Eeg==",
                            PhoneNumber = "NULL",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "LZBL3DTGYNXJPNQ3ZJ2JN3ZNI54WA4T3",
                            TwoFactorEnabled = false,
                            UserName = "user@jeuxolympiques.com"
                        });
                });

            modelBuilder.Entity("Jeux_Olympiques.Models.Cart", b =>
                {
                    b.Property<int>("RecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("RecordId"));

                    b.Property<string>("CartId")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("OfferId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("RecordId");

                    b.HasIndex("OfferId");

                    b.HasIndex("UserId");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("Jeux_Olympiques.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedId")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Entitled")
                        .HasColumnType("int");

                    b.Property<string>("Presentation")
                        .HasColumnType("longtext");

                    b.Property<int>("Site")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedId");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = 4,
                            Date = new DateTime(2024, 9, 11, 10, 15, 0, 0, DateTimeKind.Unspecified),
                            Entitled = 3,
                            Presentation = "8ème de finale Escrime Homme",
                            Site = 3
                        },
                        new
                        {
                            Id = 5,
                            Date = new DateTime(2024, 9, 12, 12, 30, 0, 0, DateTimeKind.Unspecified),
                            Entitled = 2,
                            Presentation = "Quart de finale de Natation Femme 500 mètres",
                            Site = 4
                        },
                        new
                        {
                            Id = 6,
                            Date = new DateTime(2024, 9, 11, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            Entitled = 7,
                            Presentation = "Finale Homme France - Chine",
                            Site = 3
                        });
                });

            modelBuilder.Entity("Jeux_Olympiques.Models.Offer", b =>
                {
                    b.Property<int>("OfferId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("OfferId"));

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<string>("Place")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("PublishId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Title")
                        .HasColumnType("longtext");

                    b.HasKey("OfferId");

                    b.HasIndex("EventId");

                    b.HasIndex("PublishId");

                    b.ToTable("Offers");

                    b.HasData(
                        new
                        {
                            OfferId = 14,
                            Description = "Entrée pour 1 personne",
                            EventId = 4,
                            Place = "Placement libre",
                            Price = 29m,
                            Title = "OFFRE SOLO"
                        },
                        new
                        {
                            OfferId = 15,
                            Description = "Entrée pour 2 personnes",
                            EventId = 4,
                            Place = "Placement libre",
                            Price = 55m,
                            Title = "OFFRE DUO"
                        },
                        new
                        {
                            OfferId = 16,
                            Description = "Entrée pour 4 personnes",
                            EventId = 4,
                            Place = "Placement libre",
                            Price = 100m,
                            Title = "OFFRE FAMILLE"
                        });
                });

            modelBuilder.Entity("Jeux_Olympiques.Models.Ticket", b =>
                {
                    b.Property<int>("TicketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TicketId"));

                    b.Property<string>("BuyerId")
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("ContainsOfferId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("QrCode")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("TicketDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TicketKey")
                        .HasColumnType("longtext");

                    b.HasKey("TicketId");

                    b.HasIndex("BuyerId");

                    b.HasIndex("ContainsOfferId");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("Jeux_Olympiques.Models.TicketDetail", b =>
                {
                    b.Property<int>("TicketDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TicketDetailId"));

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<int>("OfferId")
                        .HasColumnType("int");

                    b.Property<int>("TicketId")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("TicketDetailId");

                    b.HasIndex("OfferId");

                    b.HasIndex("TicketId");

                    b.ToTable("TicketDetails");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "59C78292-150C-4218-B08A-ACED1F79A45B",
                            ConcurrencyStamp = "F92315DD - 48DD - 4EA1 - A4C3 - C532D81843B6",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "1DBFDCBB-4D11-4562-9756-602889FD4163",
                            RoleId = "59C78292-150C-4218-B08A-ACED1F79A45B"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Jeux_Olympiques.Models.User", b =>
                {
                    b.HasBaseType("Jeux_Olympiques.Areas.Identity.Data.Jeux_OlympiquesUser");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasDiscriminator().HasValue("User");
                });

            modelBuilder.Entity("Jeux_Olympiques.Models.Cart", b =>
                {
                    b.HasOne("Jeux_Olympiques.Models.Offer", "Offer")
                        .WithMany("Carts")
                        .HasForeignKey("OfferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Jeux_Olympiques.Models.User", "User")
                        .WithMany("ShoppingCart")
                        .HasForeignKey("UserId");

                    b.Navigation("Offer");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Jeux_Olympiques.Models.Event", b =>
                {
                    b.HasOne("Jeux_Olympiques.Models.User", "Created")
                        .WithMany("PublishEvent")
                        .HasForeignKey("CreatedId");

                    b.Navigation("Created");
                });

            modelBuilder.Entity("Jeux_Olympiques.Models.Offer", b =>
                {
                    b.HasOne("Jeux_Olympiques.Models.Event", "Events")
                        .WithMany("Offers")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Jeux_Olympiques.Models.User", "Publish")
                        .WithMany("CreateOffer")
                        .HasForeignKey("PublishId");

                    b.Navigation("Events");

                    b.Navigation("Publish");
                });

            modelBuilder.Entity("Jeux_Olympiques.Models.Ticket", b =>
                {
                    b.HasOne("Jeux_Olympiques.Areas.Identity.Data.Jeux_OlympiquesUser", "Buyer")
                        .WithMany("BuyTicket")
                        .HasForeignKey("BuyerId");

                    b.HasOne("Jeux_Olympiques.Models.Offer", "Contains")
                        .WithMany("IsContained")
                        .HasForeignKey("ContainsOfferId");

                    b.Navigation("Buyer");

                    b.Navigation("Contains");
                });

            modelBuilder.Entity("Jeux_Olympiques.Models.TicketDetail", b =>
                {
                    b.HasOne("Jeux_Olympiques.Models.Offer", "Offer")
                        .WithMany()
                        .HasForeignKey("OfferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Jeux_Olympiques.Models.Ticket", "Ticket")
                        .WithMany("TicketDetails")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Offer");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Jeux_Olympiques.Areas.Identity.Data.Jeux_OlympiquesUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Jeux_Olympiques.Areas.Identity.Data.Jeux_OlympiquesUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Jeux_Olympiques.Areas.Identity.Data.Jeux_OlympiquesUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Jeux_Olympiques.Areas.Identity.Data.Jeux_OlympiquesUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Jeux_Olympiques.Areas.Identity.Data.Jeux_OlympiquesUser", b =>
                {
                    b.Navigation("BuyTicket");
                });

            modelBuilder.Entity("Jeux_Olympiques.Models.Event", b =>
                {
                    b.Navigation("Offers");
                });

            modelBuilder.Entity("Jeux_Olympiques.Models.Offer", b =>
                {
                    b.Navigation("Carts");

                    b.Navigation("IsContained");
                });

            modelBuilder.Entity("Jeux_Olympiques.Models.Ticket", b =>
                {
                    b.Navigation("TicketDetails");
                });

            modelBuilder.Entity("Jeux_Olympiques.Models.User", b =>
                {
                    b.Navigation("CreateOffer");

                    b.Navigation("PublishEvent");

                    b.Navigation("ShoppingCart");
                });
#pragma warning restore 612, 618
        }
    }
}
